### ISSUE TITLE
ePUB validation while loading

### ISSUE THREAD

**Issue by trekvr** [ndw/epubreader#1]
Hi,

Can you share a sample on how to validate ePUB file while loading using xsd in MarkLogic?

Regards,
Rajesh

**Comment by ndw** [comment]
You can't. I mean, you could validate the XML artifacts with XSD, but there's so much more involved in checking EPUB files that it's not likely to be worth it. The code in this project mostly assumes the EPUB files are valid.

(If you want to validate the XML files, put the schemas in the Schemas database for your appserver and run `validate strict { $doc }` where `$doc` contains the XML file.)

**Comment by trekvr** [comment]
Thanks, will try to validate against the opf file inside ePUB.

Once again thanks for your time. :)

Regards,
Rajesh
